### ISSUE TITLE
Webcam stream looks very green

### ISSUE THREAD

**Issue by cyberjak2k** [feelfreelinux/octo4a#48]
could be just a decoding issue by the client side browser, as the preview on the device looks fine. 
but the video when looking via a browser to the Octoprint control page, is as if the entire picture was washed with a bright green almost like a night vision camera. and makes it heard to see detail. I've included a picture to help. 
Phone is a GT-I9505 ( Samsung Galaxy S4) Android 5.0.1
![PXL_20211017_121921407](https://user-images.githubusercontent.com/25367182/137683353-416ec4ad-fbce-4f40-97b6-831b0b06ed03.jpg)
.

**Comment by feelfreelinux** [comment]
Looks like an issue with NV21 conversion, also reported in https://github.com/feelfreelinux/octo4a/issues/50

Will look into it soon

**Comment by de-sach** [comment]
The same behavior is present on a Xiaomi Redmi Note 3 (Running a custom Android 5.0.2 Rom)

![Screenshot from 2021-10-30 20-35-07](https://user-images.githubusercontent.com/22708763/139554781-d62d621a-9021-4212-b3c1-6a9475c6a28c.png)

When rotating the screen, the image gets split up in 4 images which are shown as below.
This image shows the spool being held on top of the printer.
![Screenshot from 2021-10-30 20-38-40](https://user-images.githubusercontent.com/22708763/139554889-e9aa65b6-5c48-487c-8035-24b651196a75.png)

Otherwise the software works really well, thank you for your hard work!

**Comment by feelfreelinux** [comment]
Resolved in: https://github.com/feelfreelinux/octo4a/commit/609071473bf2afd57adf3b8e42f5a2738b1b8798
to be released with 1.0.2

**Comment by spiceit1** [comment]
I am on the latest version (1.04) and still have the green webcam issue.

**Comment by cyberjak2k** [comment]
Well the camera works on an old Motorola E as intended , sadly it appears
the phone doesn't support OTG so can't connect to the printer

**Comment by spiceit1** [comment]
The phone is able to connect and run the printer.  The only issue is the green camera, like many have posted previously.  It said in your notes that the green camera issue was fixed in this update, but it is not fixed on the Samsung S4.  Both the front and rear cameras have a green color over the image.

Regards,


Douglas Dweck

**Comment by cyberjak2k** [comment]
They were not at my updates. I haven't posted any source code to this
project I'm just giving feedback as a general tester like you are

**Comment by DJTheCreator** [comment]
Tested on Galaxy Note 3 and also has the same green webcam problem.

**Comment by cyberjak2k** [comment]
Samsung galaxy note 4 seems to be okay and works a treat

**Comment by DJTheCreator** [comment]
So you think it's 100% to do with the phone/camera? Not any settings I can change?

**Comment by cyberjak2k** [comment]
The only way I can see this app overcoming that aspect is finding a
different way to speak to the camera module but I'm not sure how that would
be accomplished

**Comment by DragonfallGames** [comment]
It seems the Samsung S4 specifically keeps having this issue. Just got mine set up with the exact same issue.

**Comment by Yoda-Grogu** [comment]
I just set this up on my Note 3, showing green screen in window but fine when previewed as well. Everything else works great.

**Comment by Sergeykurmelev** [comment]
Hey! I connected Samsung G850f. Android 5.0.2. Also green screen. On Android 4, the application crashes and the addresses change. I stitched for android 6, the connection works, but the camera hangs and slows down.

**Comment by DJTheCreator** [comment]
I was having this issue as recently as 4 months ago but now for whatever reason, I powered on my octoprint phone again and the camera is perfect. No green at all. This was on a galaxy note 3.

**Comment by alanRfol** [comment]
Also having this issue on HTC one

**Comment by cyberjak2k** [comment]
Yes as I've tried a number of other phones and it becomes a hit and miss
kind of thing It's going to be down to how the software talks to the
underlying operating system which ultimately deals with the drivers that
talks to the camera module

**Comment by AMEND09** [comment]
This is happening to me too, but weirdly enough when I connected it to octoanywhere, on the octoanywhere dashboard the footage is fine but on the stock octoprint dashboard its green.
